name: CD (build, test deploy)

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                java: [17, 18, 19]
        steps:
        - uses: actions/checkout@v2
        - name: Setup the JDK
          id: setup-jdk
          uses: actions/setup-java@v1
          with:
              java-version: ${{matrix.java}}
        - name: Maven build & verify
          id: mvn-verify
          run: mvn -B verify
