name: test-pipeline

on:
    push:
        branches:
            - develop
            - "feature/**"
            - "hotfix/**"
    pull_request:
        branches:
            - develop
            - "feature/**"
            - "hotfix/**"

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                java: [11, 12, 13, 14, 15]
        steps:
        - uses: actions/checkout@v2
        - name: setup-jdk
          uses: actions/setup-java@v1
          with:
              java-version: ${{matrix.java}}
        - name: mvn-build
          run: mvn -B verify

